#name: Java CI with Maven
#
## Run workflow on any push or pull request to the main branch
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Checkout the repository to the GitHub Actions runner
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      # Set up JDK 11 for Maven
#      - name: Set up JDK 22
#        uses: actions/setup-java@v3
#        with:
#          java-version: '22'
#          distribution: 'adopt'
#
#      # Cache Maven dependencies to improve speed
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven
#
#      # Install dependencies and run tests
#      - name: Run tests with Maven
#        run: mvn clean test
#
#      # Archive the test results (ExtentReport)
#      - name: Archive Test Report
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: Test-Report
#          path: reports/API_Test_Report.html

name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

      - name: Archive Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test-Report
          path: reports/API_Test_Report.html
